package com.example.cielocase.domain.model

/**
 * A ticket purchase attempt.
 *
 * [id] is generated by the app before the payment starts and is sent to Cielo as the
 * order `reference`. It is the idempotency key of the whole flow: retries and duplicated
 * callbacks are always resolved against the same purchase row.
 */
data class Purchase(
    val id: String,
    val eventId: String,
    val eventTitle: String,
    val quantity: Int,
    val unitPriceInCents: Long,
    val status: PurchaseStatus,
    val createdAtEpochMillis: Long,
    val updatedAtEpochMillis: Long,
    val paymentStartedAtEpochMillis: Long? = null,
    val payment: PaymentRecord? = null,
    val failure: PaymentFailure? = null,
) {
    val totalInCents: Long get() = unitPriceInCents * quantity

    val isAwaitingPayment: Boolean
        get() = status == PurchaseStatus.PENDING && paymentStartedAtEpochMillis != null
}

enum class PurchaseStatus {
    /** Created locally, tickets reserved, no payment result yet. */
    PENDING,
    APPROVED,
    DENIED,
    CANCELLED,

    /** Integration failure: the payment could not be started or the result was unreadable. */
    FAILED,
    ;

    val isTerminal: Boolean get() = this != PENDING
}

/** Payment data returned by Cielo, kept for the receipt and for eventual reversal. */
data class PaymentRecord(
    val orderId: String?,
    val paymentId: String?,
    val authCode: String?,
    val cieloCode: String?,
    val brand: String?,
    val maskedCard: String?,
    val productName: String?,
    val installments: Int,
    val amountInCents: Long,
    val terminal: String?,
    val paidAtEpochMillis: Long?,
)

data class PaymentFailure(
    val kind: PaymentFailureKind,
    val code: Int? = null,
    val reason: String? = null,
)

enum class PaymentFailureKind {
    /** Cielo error code 1: the operator/cardholder cancelled the payment. */
    USER_CANCELLED,

    /** Cielo error code 3: transaction not authorized. */
    PAYMENT_DENIED,

    /** Cielo error code 4: invalid `clientID`/`accessToken`. */
    AUTHENTICATION,

    /** Cielo error code 2 or any unmapped code. */
    GENERIC,

    /** No app on the device handles `lio://payment` (Cielo Smart terminal/emulator missing). */
    CIELO_APP_UNAVAILABLE,

    /** Credentials were not configured in `local.properties`. */
    MISSING_CREDENTIALS,

    /** Callback received but the payload could not be decoded/parsed. */
    INVALID_RESPONSE,
}
